# argocd-marketplace-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-marketplace-binding
  namespace: openshift-marketplace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-marketplace-manager
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
  