apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4d-operator
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/Joao-VitorGD1703/cloudpak-gitops-CI-CD.git'
    targetRevision: main
    path: cp4d/operator
  destination:
    server: https://kubernetes.default.svc
    namespace: ibm-cp4d
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
