apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-catalog
  namespace: openshift-marketplace
spec:
  displayName: "IBM Cloud Pak for Data"
  publisher: "IBM"
  sourceType: grpc
  image: icr.io/cpopen/ibm-cpd-catalog:cpd_platform-4.8.4-x86_64
  updateStrategy:
    registryPoll:
      interval: 45m