apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: ibmcpd-cr
  namespace: ibm-cp4d
spec:
  license:
    accept: true
    license: Enterprise
  storageClass: managed-nfs-storage
  version: "4.8.0"